name: react_countries_app website Build and Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "Host myserver
          HostName 161.97.152.249
          User root
          IdentityFile ~/.ssh/id_ed25519
          StrictHostKeyChecking no" > ~/.ssh/config
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t react_countries_app .

    - name: Save image as tarball
      run: docker save react_countries_app | gzip > react_countries_app.tar.gz


    - name: Copy image to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "react_countries_app.tar.gz"
        target: "/tmp"
